import { useStore } from "@livestore/react";
import { createWikiContentClient } from "@oncobase/wiki-content";
import { useEffect, useRef } from "react";
import { useLocation } from "react-router";
import { cachedPageMetadata$, pageContentBySlug$, pageIndex$, pageIndexBySlug$, siteState$ } from "../livestore/queries";
import { events } from "../livestore/schema";
import { backendHref, byteSize, contentSlugFromRouteSlug, pageToEvent, readRecentSlugs, slugFromPath, storageSnapshot } from "../wiki-utils";
import { useWikiScope } from "../wiki-context";
import { canPrefetch, planPrefetch, PREFETCH_LIMITS, type CachedPage } from "./prefetch-policy";
import type { MetricsPatch } from "../types";

export const WARM_CACHE_EVENT = "wiki-vite:warm-cache";
export const FOREGROUND_FETCH_EVENT = "wiki-vite:foreground-fetch";

export function BackgroundPrefetch({ onMetrics, isForegroundBusy }: {
  onMetrics: (patch: MetricsPatch) => void;
  isForegroundBusy: () => boolean;
}) {
  const { store } = useStore();
  const scope = useWikiScope();
  const activeSlug = contentSlugFromRouteSlug(slugFromPath(useLocation().pathname));
  const active = store.useQuery(pageContentBySlug$(activeSlug));
  const state = store.useQuery(siteState$);
  const ready = Boolean(active && ["fresh", "stale"].includes(active.contentStatus) && state?.lastValidatedAt);
  const ranking = useRef({ expires: 0, slugs: [] as string[], enabled: false });
  const visits = useRef(new Map<string, number>());
  const cacheStore = useRef(store);

  useEffect(() => {
    if (!ready) return;
    if (cacheStore.current !== store) {
      cacheStore.current = store;
      ranking.current = { expires: 0, slugs: [], enabled: false };
      visits.current.clear();
    }
    let stopped = false;
    let busy = false;
    let manual = false;
    let intentSlug: string | null = null;
    let intentAnchor: HTMLAnchorElement | null = null;
    let timer: ReturnType<typeof setTimeout>;
    let idle: number | undefined;
    let controller: AbortController | undefined;
    let lastInteraction = performance.now();
    const failedUntil = new Map<string, number>();
    const client = createWikiContentClient({ scope, baseUrl: import.meta.env.VITE_WIKI_API_ORIGIN ?? "", requestTimeoutMs: 15_000 });
    const endpoint = backendHref(`/api/wiki/prefetch?scope=${scope}`);
    const navigatorHints = navigator as Navigator & { connection?: { saveData?: boolean; effectiveType?: string }; scheduling?: { isInputPending?: () => boolean } };
    const allowed = (pressure = 0) => !isForegroundBusy() && canPrefetch({ online: navigator.onLine, visible: document.visibilityState === "visible", saveData: navigatorHints.connection?.saveData, effectiveType: navigatorHints.connection?.effectiveType, pressure, inputPending: navigatorHints.scheduling?.isInputPending?.() });
    const schedule = (delay = PREFETCH_LIMITS.pauseMs) => {
      clearTimeout(timer);
      if (idle !== undefined) window.cancelIdleCallback?.(idle);
      if (!stopped) timer = setTimeout(() => {
        if (window.requestIdleCallback) idle = window.requestIdleCallback(() => { void tick(); });
        else void tick();
      }, delay);
    };
    const tick = async () => {
      if (stopped || busy) return;
      if (!allowed() || performance.now() - lastInteraction < (intentSlug ? 350 : PREFETCH_LIMITS.pauseMs)) { schedule(); return; }
      busy = true;
      controller = new AbortController();
      const signal = AbortSignal.any([controller.signal, AbortSignal.timeout(15_000)]);
      let nextDelay = PREFETCH_LIMITS.pauseMs;
      try {
        const storage = await storageSnapshot();
        if (signal.aborted || !allowed(storage.usageRatio ?? 0)) return;
        const now = Date.now();
        // Direct reader intent must not wait behind a ranking round trip.
        if (!intentSlug && ranking.current.expires <= now) {
          try {
            const response = await fetch(endpoint, { credentials: "same-origin", cache: "no-store", signal });
            if (!response.ok) {
              ranking.current.expires = now + PREFETCH_LIMITS.refreshMs;
              return;
            }
            const data = await response.json();
            if (signal.aborted) return;
            ranking.current = { expires: now + PREFETCH_LIMITS.refreshMs, enabled: data.enabled === true,
              slugs: Array.isArray(data.slugs) ? data.slugs.filter((slug: unknown): slug is string => typeof slug === "string").slice(0, 200) : [] };
          } catch (error) {
            // Failures and timeouts back off, but yielding to navigation or
            // foreground work must not poison the next route's ranking cache.
            if (!controller.signal.aborted) ranking.current.expires = now + PREFETCH_LIMITS.refreshMs;
            throw error;
          }
        }
        // Visits are generated by visible navigation, never by prefetch GETs.
        // Dedupe repeated renders/reloads within this mounted reader session.
        if (!intentSlug && ranking.current.enabled && now - (visits.current.get(activeSlug) ?? 0) >= 10 * 60_000) {
          visits.current.set(activeSlug, now);
          if (visits.current.size > 200) visits.current.delete(visits.current.keys().next().value!);
          await fetch(endpoint, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug: activeSlug }), signal });
        }
        if (signal.aborted || !allowed()) return;
        const index = store.query(pageIndex$);
        const cached = store.query(cachedPageMetadata$) as CachedPage[];
        const requestedSlug = intentSlug;
        intentSlug = null;
        const { queue, evict } = planPrefetch({ activeSlug, recent: requestedSlug ? [requestedSlug, ...readRecentSlugs()] : readRecentSlugs(), ranked: manual ? [...ranking.current.slugs, ...index.slice(0, 80).map(page => page.slug)] : ranking.current.slugs, index, cached });
        if (evict.length) store.commit(events.pageContentEvicted({ slugs: evict }));
        const slug = queue.find(candidate => (!requestedSlug || candidate === requestedSlug) && (failedUntil.get(candidate) ?? 0) <= now);
        if (!slug) { nextDelay = 30_000; return; }
        failedUntil.set(slug, now + PREFETCH_LIMITS.refreshMs);
        const batch = await client.fetchPages({ slugs: [slug], signal });
        if (signal.aborted || stopped) return;
        const page = batch.pages.find(page => page.slug === slug);
        if (!page || (scope === "public" && page.sensitive)) return;
        const bytes = byteSize(page.content);
        const otherBytes = (store.query(cachedPageMetadata$) as CachedPage[]).reduce((sum, row) => sum + (row.slug === slug ? 0 : row.size), 0);
        if (otherBytes + bytes > PREFETCH_LIMITS.bytes) return;
        store.commit(pageToEvent(page));
        failedUntil.delete(slug);
      } catch {
        // Best effort: background failures never replace the foreground UI or
        // print authenticated request details. Retry on a later bounded cycle.
      } finally { busy = false; schedule(intentSlug ? 350 : nextDelay); }
    };
    const interrupt = () => { intentSlug = null; intentAnchor = null; lastInteraction = performance.now(); controller?.abort(); schedule(); };
    const onIntent = (event: Event) => {
      // Delegation covers document and sidebar links without adding a
      // listener or a store subscription to every item in a large navigation tree.
      const anchor = event.target instanceof Element ? event.target.closest("a[href]") : null;
      if (!(anchor instanceof HTMLAnchorElement) || anchor === intentAnchor || anchor.hasAttribute("download") || (anchor.target && anchor.target !== "_self")) return;
      if (event instanceof PointerEvent && event.pointerType !== "mouse") return;
      let slug: string;
      try {
        const url = new URL(anchor.href);
        if (url.origin !== location.origin || url.search || url.pathname === location.pathname) return;
        slug = contentSlugFromRouteSlug(slugFromPath(url.pathname));
      } catch { return; }
      const candidate = store.query(pageIndexBySlug$(slug));
      if (!candidate || slug === activeSlug || (scope === "public" && candidate.sensitive) || !allowed()) return;
      intentAnchor = anchor;
      intentSlug = slug;
      // A short dwell filters pointer flyovers. An already-running request stays
      // serial; its next turn will service the latest intent first.
      schedule(350);
    };
    const onLeave = (event: Event) => {
      const next = (event as FocusEvent | PointerEvent).relatedTarget;
      if (intentAnchor && event.target instanceof Node && intentAnchor.contains(event.target) && !(next instanceof Node && intentAnchor.contains(next))) {
        intentSlug = null;
        intentAnchor = null;
        schedule();
      }
    };
    const warm = () => { manual = true; onMetrics({ status: "ready", message: "Queued background cache warming" }); schedule(); };
    for (const event of ["pointerdown", "keydown", "wheel", "touchstart"]) window.addEventListener(event, interrupt, { passive: true });
    document.addEventListener("visibilitychange", interrupt);
    window.addEventListener("offline", interrupt);
    window.addEventListener("online", interrupt);
    window.addEventListener(FOREGROUND_FETCH_EVENT, interrupt);
    window.addEventListener(WARM_CACHE_EVENT, warm);
    document.addEventListener("pointerover", onIntent);
    document.addEventListener("focusin", onIntent);
    document.addEventListener("pointerout", onLeave);
    document.addEventListener("focusout", onLeave);
    schedule();
    return () => {
      stopped = true;
      document.removeEventListener("pointerover", onIntent);
      document.removeEventListener("focusin", onIntent);
      document.removeEventListener("pointerout", onLeave);
      document.removeEventListener("focusout", onLeave);
      clearTimeout(timer);
      if (idle !== undefined) window.cancelIdleCallback?.(idle);
      controller?.abort();
      for (const event of ["pointerdown", "keydown", "wheel", "touchstart"]) window.removeEventListener(event, interrupt);
      document.removeEventListener("visibilitychange", interrupt);
      window.removeEventListener("offline", interrupt);
      window.removeEventListener("online", interrupt);
      window.removeEventListener(FOREGROUND_FETCH_EVENT, interrupt);
      window.removeEventListener(WARM_CACHE_EVENT, warm);
    };
  }, [activeSlug, ready, scope, state?.manifestHash, store, onMetrics, isForegroundBusy]);
  return null;
}
