import { readdirSync } from "node:fs";
import path from "node:path";

// Vercel serves static files before the authentication catch-all. Every file
// here is deliberately anonymous; adding a new one requires explicit review.
const PUBLIC_FILES = new Set([
  "auth-wiki-cartoon-dark.png",
  "auth-wiki-cartoon-light.png",
  "favicon.svg",
  "robots.txt",
  // Agent-readable feature lists, generated by scripts/build-llms-txt.ts.
  "llms.txt",
  "llms-full.txt",
  // Curated Diana visuals requested for the anonymous landing page.
  // Sources and capture review: specs/landing-page.md. Keep this file-specific.
  "landing/immune-recognition-light.webp",
  "landing/immune-recognition-dark.webp",
  "landing/cell-therapy-family-light.webp",
  "landing/cell-therapy-family-dark.webp",
  "landing/molecular-layers-light.webp",
  "landing/molecular-layers-dark.webp",
  "landing/reader-desktop-light.jpg",
  "landing/reader-desktop-dark.jpg",
  "landing/reader-mobile-light.jpg",
  "landing/reader-mobile-dark.jpg",
  "landing/diagnostics-timeline-dark.jpg",
  "landing/diagnostics-timeline-light.jpg",
  "landing/dicom-viewer.jpg",
  "landing/og-image.jpg",
  // Sample-content screenshots for the public features page.
  // Sources and capture method: specs/features-page.md.
  "feature-shots/ai-search-dark.jpg",
  "feature-shots/ai-search-light.jpg",
  "feature-shots/mobile-nav-dark.jpg",
  "feature-shots/mobile-nav-light.jpg",
  "feature-shots/mobile-outline-dark.jpg",
  "feature-shots/mobile-outline-light.jpg",
  "feature-shots/mobile-page-dark.jpg",
  "feature-shots/mobile-page-light.jpg",
  "feature-shots/palette-dark.jpg",
  "feature-shots/palette-light.jpg",
  "feature-shots/reader-dark.jpg",
  "feature-shots/reader-light.jpg",
  "feature-shots/table-narrow-dark.jpg",
  "feature-shots/table-narrow-light.jpg",
  "feature-shots/table-wide-dark.jpg",
  "feature-shots/table-wide-light.jpg",
  "landing/sign-in-cartoon-light.webp",
  "landing/sign-in-cartoon-dark.webp",
]);

function files(directory: string, prefix = ""): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const relative = prefix + entry.name;
    if (entry.isSymbolicLink()) {
      throw new Error(`Public assets cannot contain symbolic links: ${relative}`);
    }
    if (entry.isDirectory()) return files(path.join(directory, entry.name), `${relative}/`);
    if (!entry.isFile()) throw new Error(`Unexpected public asset type: ${relative}`);
    return [relative];
  });
}

export function assertPublicAssets(directory: string) {
  const unexpected = files(directory).filter((file) => !PUBLIC_FILES.has(file));
  if (unexpected.length) {
    throw new Error(`Unapproved anonymous public assets: ${unexpected.join(", ")}. Reader documents must use authenticated content routes.`);
  }
}

export function assertBuildAssets(directory: string) {
  const unexpected = files(directory).filter((file) => {
    // The one SPA entry is embedded into the gated function and removed from
    // Vercel's static output by build-vercel-functions.ts.
    if (file === "index.html" || PUBLIC_FILES.has(file)) return false;
    return !file.startsWith("assets/") || /\.(?:html?|xhtml)$/i.test(file);
  });
  if (unexpected.length) {
    throw new Error(`Unapproved static build output: ${unexpected.join(", ")}`);
  }
}
