/**
 * The single source for the public comparison page and its markdown twin
 * (`public/compare.md`, generated by `scripts/build-llms-txt.ts`).
 *
 * Facts about other products come from their own public sites and repositories
 * as of October 2026. Say "Not stated" rather than guess, keep claims modest,
 * and re-check a product before changing what we say about it.
 */
import { REPO_URL, SITE_URL } from "./features-data";

export const COMPARE_ASOF = "October 2026";

export const compareHeroLede =
  "Most people don’t need to build anything. Start with the simplest tool that does the job, and reach for Oncobase when you want a private, shareable knowledge base you control, or you’re building your own.";

export const compareDisclosure =
  "We make Oncobase, so we’re not neutral. What we say about other products comes from their own sites and repositories as of October 2026. Check before you decide, and tell us what we got wrong.";

export const notSure =
  "Not sure? Start with Notion to share with family today, or Obsidian to keep everything private on your own computer. If you want help researching your case, look at Yuga Bio. Come back if you outgrow them.";

export type ProductId = "notion" | "obsidian" | "yuga" | "citizen" | "mere" | "medplum" | "oncobase";

export type Product = {
  id: ProductId;
  name: string;
  url: string;
  kind: string;
  tagline: string;
  great: string;
  consider: string;
};

export const products: Product[] = [
  {
    id: "notion",
    name: "Notion",
    url: "https://www.notion.com/",
    kind: "Shared workspace",
    tagline: "An all-in-one workspace for docs, databases, and projects, with AI and sharing built in.",
    great: "Quick to start and easy to share with family. Databases work well for appointments, medications, and questions for the care team.",
    consider:
      "It isn’t built for medical records. Notion signs a HIPAA business associate agreement only on its Enterprise plan, so check its terms before storing anything sensitive.",
  },
  {
    id: "obsidian",
    name: "Obsidian",
    url: "https://obsidian.md/",
    kind: "Private notes",
    tagline: "Notes as plain markdown files on your device, with optional paid sync and publishing.",
    great:
      "Your notes stay yours, in an open file format. The app is free, Sync is end-to-end encrypted, shared vaults let you collaborate, and community plugins fill gaps.",
    consider:
      "You run it yourself. A read-only site for family, roles, search by meaning, and redaction need plugins or something built on top. Oncobase publishes an Obsidian-style folder of markdown, so the two work together.",
  },
  {
    id: "yuga",
    name: "Yuga Bio",
    url: "https://yugabio.com/",
    kind: "Hosted AI research workspace",
    tagline: "Upload your records and AI agents research trials, literature, and molecular context for your case.",
    great:
      "Turns records into a structured case file, searches open biomedical literature, and searches 13 trial registries. It de-identifies uploads before its AI sees them, says it doesn’t train on your data, and lets you invite others into a shared workspace.",
    consider:
      "It’s a hosted, proprietary service with paid plans ($20, $50, and $100 a month, plus custom), offered to people in the United States. A business associate agreement covers providers and custom plans.",
  },
  {
    id: "citizen",
    name: "Citizen Health",
    url: "https://www.citizen.health/",
    kind: "Records plus an AI companion",
    tagline: "Gathers records from your providers and adds an AI companion that answers questions and handles paperwork.",
    great:
      "Centralizes records from many providers, tracks symptoms, and drafts insurance appeals, forms, and scheduling with your approval. It cites SOC 2 Type II.",
    consider:
      "Free in early access, with pricing still to come, and a proprietary service. It serves rare and complex conditions as well as cancer.",
  },
  {
    id: "mere",
    name: "Mere Medical",
    url: "https://github.com/cfu288/mere-medical",
    kind: "Self-hosted records",
    tagline: "An open-source, self-hosted app that pulls your records from patient portals into one timeline.",
    great:
      "Syncs records from the patient portals of thousands of hospitals and clinics onto a server you run, so they stay in your hands. MIT licensed.",
    consider:
      "Maintained by one developer, and it’s a records tool, not a notes or research workspace.",
  },
  {
    id: "medplum",
    name: "Medplum",
    url: "https://www.medplum.com/",
    kind: "Developer platform",
    tagline: "An open-source (Apache 2.0) platform for building clinical software on FHIR.",
    great:
      "A serious foundation if you’re building a product: FHIR-native storage, an API, authentication, automation, and managed hosting. Its site cites HIPAA and SOC 2 compliance.",
    consider: "It’s infrastructure for builders, not an app a family can use on its own.",
  },
  {
    id: "oncobase",
    name: "Oncobase",
    url: REPO_URL,
    kind: "Open-source knowledge base",
    tagline: "An open-source knowledge base for taking control of your care.",
    great:
      "Publishes a vault of notes, papers, and results to a searchable reader with chat, semantic search, roles, inline redaction, comments, and scan and slide viewers. MIT licensed, with a CLI and files built for agents.",
    consider:
      "You set it up and host it, or have your agent do it. It organizes what you bring and can import labs from Epic MyChart, but it doesn’t gather your records or match trials for you. It carries no compliance certification, so you own how it’s hosted.",
  },
];

export const matrixColumns: ProductId[] = ["notion", "obsidian", "yuga", "citizen", "mere", "medplum", "oncobase"];

export type Cell = { t: string; tone?: "yes" | "no" | "unknown" };
const y = (t: string): Cell => ({ t, tone: "yes" });
const n = (t: string): Cell => ({ t, tone: "no" });
const u = (t = "Not stated"): Cell => ({ t, tone: "unknown" });
const c = (t: string): Cell => ({ t });

/** One row per question; cells follow `matrixColumns`. */
export const matrix: { label: string; cells: Cell[] }[] = [
  {
    label: "Where your data lives",
    cells: [c("Hosted"), y("Your device"), c("Hosted"), c("Hosted"), y("Your server"), c("Managed or self-hosted"), y("Your accounts or server")],
  },
  {
    label: "Open source",
    cells: [n("No"), n("No (open file format)"), n("No"), u(), y("Yes (MIT)"), y("Yes (Apache 2.0)"), y("Yes (MIT)")],
  },
  {
    label: "Cost",
    cells: [
      c("Free and paid tiers"),
      c("Free app; paid Sync and Publish"),
      c("$20–$100 a month, plus custom"),
      c("Free in early access"),
      c("Self-host"),
      c("Free core; paid hosting"),
      c("Free; you pay for hosting"),
    ],
  },
  {
    label: "Bring in medical records",
    cells: [
      c("Paste or attach"),
      c("Paste or attach"),
      y("Upload documents and genomics"),
      y("Retrieves from providers"),
      y("Syncs from patient portals"),
      c("You build it (FHIR)"),
      c("Bring your files; optional Epic labs"),
    ],
  },
  {
    label: "AI over your content",
    cells: [y("Notion AI"), c("Through plugins"), y("Agents research your case"), y("AI companion"), u(), u(), y("Chat agent and semantic search")],
  },
  {
    label: "Trial and literature search",
    cells: [n("Not built in"), n("Not built in"), y("13 registries and open literature"), u(), u(), c("You build it"), c("CLI helpers for literature and trials")],
  },
  {
    label: "Share with family and the care team",
    cells: [y("Sharing and permissions"), y("Shared vaults"), y("Shared workspace"), u(), u(), c("You build it"), y("Roles by folder and tag, plus comments")],
  },
  {
    label: "Hide names inside a page",
    cells: [n("Not built in"), n("Not built in"), y("De-identifies uploads"), u(), u(), u(), y("Inline redaction wherever text leaves")],
  },
  {
    label: "Scan and slide viewers",
    cells: [n("Not built in"), n("Not built in"), u(), u(), u(), u(), y("DICOM and pathology viewers")],
  },
  {
    label: "Compliance statements",
    cells: [c("BAA on Enterprise plan"), u(), c("BAA for providers and custom plans"), y("SOC 2 Type II"), u(), y("HIPAA and SOC 2 (managed)"), n("None; you own how it’s hosted")],
  },
  {
    label: "Open interfaces for your own tools",
    cells: [c("API"), y("Plugin API"), u(), u(), c("Open source code"), y("FHIR API and SDK"), y("CLI, JSON API, and /features.md")],
  },
];

export type Goal = {
  id: string;
  label: string;
  pick: ProductId;
  also: ProductId[];
  why: string;
  moveOn: string;
};

/** The "which should I use?" list. Most people should pick something simpler than Oncobase. */
export const goals: Goal[] = [
  {
    id: "share",
    label: "Keep notes and share them with my family",
    pick: "notion",
    also: ["obsidian"],
    why: "Notion is the quickest way to get everyone on the same page, with sharing built in.",
    moveOn: "Move to Oncobase if different people should see different pages, or names should be hidden inside a page.",
  },
  {
    id: "private",
    label: "Keep everything private on my own computer",
    pick: "obsidian",
    also: ["notion"],
    why: "Obsidian keeps plain markdown files on your device, free, with paid encrypted sync if you want it.",
    moveOn: "Oncobase publishes an Obsidian-style folder, so you can start in Obsidian and add a private reader later.",
  },
  {
    id: "research",
    label: "Turn my records into research and trial matches",
    pick: "yuga",
    also: ["citizen"],
    why: "Yuga Bio is built for this: records in, a structured case file and trial search out.",
    moveOn: "Add Oncobase when you want a lasting, shareable knowledge base you control alongside the research.",
  },
  {
    id: "records",
    label: "Collect records from all my providers",
    pick: "citizen",
    also: ["mere"],
    why: "Citizen Health retrieves records for you. Mere Medical does it on your own server if you prefer self-hosting.",
    moveOn: "Oncobase organizes what you gather into notes, papers, and results people can read.",
  },
  {
    id: "knowledge",
    label: "Give my family and care team a private, searchable knowledge base",
    pick: "oncobase",
    also: ["notion", "yuga"],
    why: "This is what Oncobase is for: roles, sensitive pages, inline redaction, chat and semantic search, and scan and slide viewers.",
    moveOn: "It asks more of you than Notion or Yuga Bio. If you only need notes or research, start there.",
  },
  {
    id: "build",
    label: "I’m building my own product",
    pick: "oncobase",
    also: ["medplum", "mere"],
    why: "Oncobase is MIT licensed, so you can reuse the reader, tables, chat, comments, and viewers. Medplum covers the clinical data layer, and Mere Medical covers pulling records from portals.",
    moveOn: "Have your agent read /features.md first. It lists every feature and interface.",
  },
];

export type Piece = { name: string; license: string; gives: string; url: string };

/** Reusable code in the Oncobase repository. Only the CLI is published to npm; the rest lives under `packages/`. */
export const oncobasePieces: Piece[] = [
  { name: "@oncobase/smart-table", license: "MIT", gives: "Tables that size columns to their content, with resize handles and expand-to-fill.", url: `${REPO_URL}/tree/main/packages/smart-table` },
  { name: "@oncobase/wiki-markdown", license: "MIT", gives: "A markdown renderer with wikilinks, citations, math, Mermaid, and the smart tables.", url: `${REPO_URL}/tree/main/packages/wiki-markdown` },
  { name: "@oncobase/wiki-shell", license: "MIT", gives: "The reader’s navigation, header, outline, search, and layout pieces.", url: `${REPO_URL}/tree/main/packages/wiki-shell` },
  { name: "@oncobase/chat", license: "MIT", gives: "A full-stack chat UI with streaming and saved conversations.", url: `${REPO_URL}/tree/main/packages/chat` },
  { name: "@oncobase/wiki-comments", license: "MIT", gives: "Comment threads on pages and selections, built on Liveblocks.", url: `${REPO_URL}/tree/main/packages/wiki-comments` },
  { name: "@oncobase/diagnostics", license: "MIT", gives: "The diagnostics timeline and study helpers. The scan and slide viewers live in the app.", url: `${REPO_URL}/tree/main/packages/diagnostics` },
  { name: "@oncobase/wiki-content", license: "MIT", gives: "Content contracts, privacy helpers for hiding personal details, and embeddings.", url: `${REPO_URL}/tree/main/packages/wiki-content` },
  { name: "@oncobase/oncobase (CLI)", license: "MIT", gives: "Check, sync, and publish a vault in a few commands. The one package on npm.", url: "https://www.npmjs.com/package/@oncobase/oncobase" },
];

/** Open-source projects worth building on, with what each does and the license. */
export const otherOpenSource: Piece[] = [
  { name: "Medplum", license: "Apache 2.0", gives: "FHIR-native storage, authentication, an API, and automation for clinical software.", url: "https://github.com/medplum/medplum" },
  { name: "Mere Medical", license: "MIT", gives: "Pulls records from patient portals into a self-hosted timeline.", url: "https://github.com/cfu288/mere-medical" },
  { name: "Cornerstone3D", license: "MIT", gives: "The DICOM imaging engine behind Oncobase’s scan viewer.", url: "https://github.com/cornerstonejs/cornerstone3D" },
  { name: "OpenSeadragon", license: "BSD 3-Clause", gives: "The zoomable image viewer behind Oncobase’s whole-slide pathology viewer.", url: "https://github.com/openseadragon/openseadragon" },
];

export const alsoWorthKnowing: { name: string; url: string; text: string }[] = [
  {
    name: "osteosarc.com",
    url: "https://osteosarc.com/",
    text: "Sid Sijbrandij’s openly shared tumor genomics, imaging, and timeline data. It inspired Oncobase, and shows what sharing your own data openly can look like.",
  },
  {
    name: "OnCo technologies",
    url: "https://onco.cc/technologies/",
    text: "A browsable catalog of 765 cancer technologies. A reference for what exists, to use alongside any of the above.",
  },
  {
    name: "Healthier Intelligence",
    url: "https://www.healthier.inc/",
    text: "Early: its site shows a tagline and a contact address and no product details yet, so there is nothing to compare.",
  },
  {
    name: "Fasten Health",
    url: "https://github.com/fastenhealth/fasten-onprem",
    text: "A self-hosted family record manager (GPL-3.0). Its on-premise repository is archived and read-only, and it supported manual entry and FHIR uploads rather than syncing from providers. Mere Medical is the active alternative.",
  },
];

export const compareSources: { name: string; url: string }[] = [
  { name: "Notion HIPAA guidance", url: "https://www.notion.com/help/hipaa" },
  { name: "Yuga Bio", url: "https://yugabio.com/" },
  { name: "Citizen Health", url: "https://www.citizen.health/" },
  { name: "Obsidian", url: "https://obsidian.md/" },
  { name: "Mere Medical README", url: "https://github.com/cfu288/mere-medical" },
  { name: "Medplum", url: "https://www.medplum.com/" },
];

/** Table order: Oncobase first, as the reference column that stays in view, then the rest. */
export const matrixOrder: ProductId[] = ["oncobase", ...matrixColumns.filter((id) => id !== "oncobase")];
export const cellFor = (row: { cells: Cell[] }, id: ProductId): Cell => row.cells[matrixColumns.indexOf(id)]!;

const productById = (id: ProductId) => products.find((product) => product.id === id)!;
export const productName = (id: ProductId) => productById(id).name;

/** The text of `public/compare.md`, the markdown twin of /compare. */
export function renderCompareMd(): string {
  const goalsMd = goals
    .map(
      (goal) =>
        `- **${goal.label}:** start with ${productName(goal.pick)}${goal.also.length ? ` (also consider ${goal.also.map(productName).join(", ")})` : ""}. ${goal.why} ${goal.moveOn}`,
    )
    .join("\n");
  const cards = products
    .map(
      (product) =>
        `### ${product.name}\n\n${product.kind}. ${product.tagline} ${product.url}\n\n- **Great at:** ${product.great}\n- **Consider:** ${product.consider}`,
    )
    .join("\n\n");
  const head = ["Question", ...matrixOrder.map(productName)];
  const table = [
    `| ${head.join(" | ")} |`,
    `| ${head.map(() => "---").join(" | ")} |`,
    ...matrix.map((row) => `| ${row.label} | ${matrixOrder.map((id) => cellFor(row, id).t).join(" | ")} |`),
  ].join("\n");
  const pieceTable = (pieces: Piece[]) =>
    ["| Piece | License | What you get |", "| --- | --- | --- |", ...pieces.map((p) => `| [${p.name}](${p.url}) | ${p.license} | ${p.gives} |`)].join("\n");
  const also = alsoWorthKnowing.map((item) => `- [${item.name}](${item.url}): ${item.text}`).join("\n");
  const sources = compareSources.map((source) => `- [${source.name}](${source.url})`).join("\n");
  return `# How Oncobase compares

${compareHeroLede}

${compareDisclosure}

${notSure}

Page: ${SITE_URL}/compare. Source: ${REPO_URL}. Agent-readable feature list: ${SITE_URL}/features.md.

## Which should I use?

${goalsMd}

## Side by side

${table}

"Not stated" means the product's public site or repository doesn't say.

## Each option

${cards}

## If you're building your own

Oncobase is MIT licensed, so a family or a company can reuse it, and an agent can read /features.md to see everything it offers. If you handle other people's health information, check which rules apply to you: Oncobase carries no compliance certification.

### Reusable code in Oncobase

Only the CLI is on npm. The rest lives under \`packages/\` in the repository.

${pieceTable(oncobasePieces)}

### Other open-source projects worth building on

${pieceTable(otherOpenSource)}

## Also worth knowing

${also}

## Sources

${sources}

Checked ${COMPARE_ASOF}.
`;
}
