/**
 * The single source for the public features page and the agent-readable files
 * (`public/llms.txt`, `public/llms-full.txt`, generated by
 * `scripts/build-llms-txt.ts`). Only list what the code really does.
 */

export const REPO_URL = "https://github.com/jasonLaster/oncobase";
export const SITE_URL = "https://diana-tnbc.com";

export type GroupId = "read" | "ask" | "protect" | "data" | "share" | "build";

export type Feature = {
  group: GroupId;
  name: string;
  /** One plain sentence about what it does for the person using it. */
  summary: string;
  /** Where you find it. */
  where: string;
  /** How an agent or script reaches it, when it can. */
  surface?: string;
};

export const groups: { id: GroupId; title: string; tagline: string }[] = [
  { id: "read", title: "Read", tagline: "Find your way around and read comfortably, on any screen." },
  { id: "ask", title: "Ask", tagline: "Search by meaning, or talk to the knowledge base." },
  { id: "protect", title: "Protect", tagline: "Share the science without sharing the patient." },
  { id: "data", title: "See the data", tagline: "Timelines, scans, and slides next to the notes." },
  { id: "share", title: "Share", tagline: "Bring family, doctors, and researchers in." },
  { id: "build", title: "Build", tagline: "Publish from plain files. Extend it with code or agents." },
];

export const features: Feature[] = [
  // Read
  { group: "read", name: "Page tree", summary: "Every page in a folders-first tree that remembers what you opened, resizes, collapses to a rail, and stays fast on large vaults.", where: "Sidebar", surface: "GET /api/wiki/manifest" },
  { group: "read", name: "Outline", summary: "A page's headings with the current section highlighted as you scroll; a tab in the phone sheet and a mode in the palette.", where: "Right rail, phone sheet, palette (⌘⇧O)" },
  { group: "read", name: "Heading links", summary: "Every heading is linkable. Hover for a # that copies the URL, and deep links land clear of the fixed header.", where: "Every page" },
  { group: "read", name: "Smart tables", summary: "Column widths come from measured text, drag to resize, expand to the full workspace on desktop, with a phone layout and a sticky first column.", where: "Any markdown table" },
  { group: "read", name: "File palette", summary: "⌘K jumps to any page with fuzzy matching and recents, works offline, and also finds headings, source PDFs, tags, and actions.", where: "⌘K / Ctrl+K" },
  { group: "read", name: "Mobile reader", summary: "A phone header, a bottom sheet with Page nav and Outline tabs, focus trapping, and a floating Ask wiki button.", where: "Below 768px" },
  { group: "read", name: "Light, dark, or system", summary: "Three theme modes applied before first paint, so there is no flash. Diagrams follow the theme.", where: "Actions menu, palette, theme button" },
  { group: "read", name: "Image lightbox and slides", summary: "Open any image full screen with download, and step through a slide set with the arrow keys.", where: "Every page with images" },
  { group: "read", name: "Rich markdown", summary: "Wikilinks, GFM tables, task lists and footnotes, KaTeX math, Mermaid diagrams, citation links, and PDF chips.", where: "Every page" },
  { group: "read", name: "Tags and note bundles", summary: "Tag pages list their pages as a tree; Overview, Formatted, and Raw versions of one note share a switcher.", where: "/tags/:tag, page header" },
  { group: "read", name: "Saved pages and offline", summary: "Pages are stored on your device, paint before the database opens, and say plainly when you are offline or retrying.", where: "Automatic" },
  { group: "read", name: "Copy and download", summary: "Copy a page as markdown in one click, or download the whole wiki as a zip.", where: "Page header, actions menu", surface: "GET /api/page-copy, GET /api/download" },
  // Ask
  { group: "ask", name: "Chat with the knowledge base", summary: "An agent searches, reads the best pages, follows links, and answers with inline citations. Conversations are saved, and you can stop, queue, and resume.", where: "Ask wiki, /chat", surface: "POST /api/chat" },
  { group: "ask", name: "AI search", summary: "Semantic search that returns the most relevant pages, each scored out of 10 with a one-line reason.", where: "/search (AI Mode)", surface: "POST /api/ai-search" },
  { group: "ask", name: "Text search", summary: "Exact matches with line numbers and highlighted snippets, grouped by page, with an interim answer while the full scan finishes.", where: "/search (Text Search)", surface: "GET /api/search" },
  { group: "ask", name: "Agent tools", summary: "The same search and read tools the chat agent uses, as a JSON endpoint: search_wiki, read_page, get_pages_by_tag, list_tags, list_pages.", where: "API only", surface: "POST /api/tools" },
  // Protect
  { group: "protect", name: "Password gate", summary: "A shared password in front of the whole site, with a signed cookie and no-store responses.", where: "Sign-in page", surface: "POST /api/login" },
  { group: "protect", name: "Accounts and roles", summary: "Give each person a role and choose which folders and tags they can open. A sensitive page that no role matches is visible to nobody.", where: "Admin, Roles", surface: "/api/admin/roles" },
  { group: "protect", name: "Sensitive pages", summary: "Mark a page sensitive in its frontmatter and it drops out of guest manifests, search, AI search, chat, tags, downloads, link previews, and comments.", where: "Frontmatter", surface: "oncobase check" },
  { group: "protect", name: "Inline redaction", summary: "Wrap a span in <redact> or a block in :::redact and readers without access see the label, not the text.", where: "Markdown" },
  { group: "protect", name: "Redaction patterns", summary: "Per-site patterns catch identifiers that slip through, applied on page reads, search, AI search, chat, copy, and downloads.", where: "Site config" },
  { group: "protect", name: "Admin screens", summary: "Filter pages by who can see them, assign roles in bulk, and preview what a role includes before saving.", where: "/admin/pages, /admin/users, /admin/roles" },
  { group: "protect", name: "Agent skills for redaction", summary: "Written rules teach agents what to redact, what to leave visible, and what to mark sensitive, with a linter that checks.", where: "Vault skills (Diana’s vault)" },
  // See the data
  { group: "data", name: "Diagnostics timeline", summary: "Swim-lanes for imaging, pathology, ctDNA, and blood counts, with a draggable overview, zoom, filter, and source links.", where: "/diagnostics", surface: "GET /api/timeline" },
  { group: "data", name: "Imaging list", summary: "Every study with its reports, images, comparisons, and download, as a table or a phone list.", where: "/diagnostics/imaging", surface: "GET /api/diagnostic-studies" },
  { group: "data", name: "DICOM viewer", summary: "Stack and series browsing, window/level, pan, zoom, cine, touch gestures, deep links, and saved annotations with a calibrated ruler.", where: "/tools/dicom-viewer", surface: "/api/dicom/*" },
  { group: "data", name: "DICOM compare", summary: "Two synced viewports with presets such as subtraction, z-matched, and projection, and a clear match state.", where: "/tools/dicom-compare" },
  { group: "data", name: "Pathology slides", summary: "Whole-slide viewing with a navigator, magnification, scale bar, rulers, side-by-side compare, and saved region notes.", where: "/tools/pathology-viewer", surface: "/api/pathology/*" },
  { group: "data", name: "Lab ingestion", summary: "An hourly import of lab results from Epic MyChart over SMART on FHIR, with encrypted tokens.", where: "Admin", surface: "/api/integrations/epic/*" },
  // Share
  { group: "share", name: "Comments", summary: "Page-level and selection-anchored threads with replies, reactions, resolve, and shareable links; guests get a stable name.", where: "Right rail, /comments", surface: "/api/liveblocks-*" },
  { group: "share", name: "Link previews", summary: "Pages get their own preview card in chats and social apps. Sensitive pages fall back to a generic card.", where: "Automatic", surface: "GET /api/share-preview" },
  { group: "share", name: "Education hub", summary: "A public, password-free reader for the guides you choose to share, with its own search.", where: "/education", surface: "GET /api/education/*" },
  { group: "share", name: "Multi-site", summary: "One deployment can serve several sites, each with its own domain, password, roles, and data.", where: "Site config" },
  // Build
  { group: "build", name: "Publish from a vault", summary: "Write in an Obsidian-style folder of markdown and publish with one command. Only changed files upload.", where: "Terminal", surface: "oncobase publish" },
  { group: "build", name: "Dry runs and safety rails", summary: "check shows what would change, tombstones need an explicit flag, dirty trees are refused, and uploads are verified by reading them back.", where: "Terminal", surface: "oncobase check" },
  { group: "build", name: "Sync", summary: "Pull remote content into the vault without overwriting your edits; differences are set aside for review.", where: "Terminal", surface: "oncobase sync" },
  { group: "build", name: "Embeddings", summary: "Publishing computes search embeddings so semantic search works the moment a page goes live.", where: "Terminal", surface: "oncobase publish --embeddings" },
  { group: "build", name: "Research helpers", summary: "Literature and clinical-trial search with provenance, and audio-to-note transcription.", where: "Terminal", surface: "oncobase elicit, oncobase transcription" },
  { group: "build", name: "Agent skills", summary: "Skills for first-time setup and safe pre-publish checks ship with the CLI and copy into your vault.", where: "Terminal", surface: "oncobase skills" },
  { group: "build", name: "Local stack", summary: "A self-hosted backend, seeded site, and smoke test on your machine, with no cloud account.", where: "Terminal", surface: "bun run local:stack" },
  { group: "build", name: "Open source", summary: "MIT licensed. Run it on Vercel and Convex or with the standalone Bun server.", where: "GitHub" },
];

export const groupFeatures = (id: GroupId) => features.filter((feature) => feature.group === id);

/** Interfaces an agent or script can use. Auth: Gate = shared password cookie. */
export const interfaces: { name: string; kind: "API" | "CLI" | "Script"; does: string; auth: string }[] = [
  { name: "GET /api/wiki/manifest", kind: "API", does: "File tree, page index, and asset index with ETag", auth: "Gate" },
  { name: "GET /api/wiki/pages?slugs=", kind: "API", does: "Page bodies, redacted for the viewer", auth: "Gate" },
  { name: "GET /api/search?q=", kind: "API", does: "Exact-text search with line hits", auth: "Gate" },
  { name: "POST /api/ai-search", kind: "API", does: "Semantic search with relevance scores and summaries", auth: "Gate" },
  { name: "POST /api/chat", kind: "API", does: "Streaming agent chat with citations", auth: "Gate" },
  { name: "POST /api/tools", kind: "API", does: "Run search_wiki, read_page, get_pages_by_tag, list_tags, list_pages", auth: "Gate" },
  { name: "GET /api/page-copy?slug=", kind: "API", does: "A page as a markdown download", auth: "Gate" },
  { name: "GET /api/download?type=", kind: "API", does: "The whole wiki as a zip", auth: "Gate" },
  { name: "GET /api/file?path=", kind: "API", does: "A PDF, image, or data file, with range requests", auth: "Gate" },
  { name: "GET /api/timeline", kind: "API", does: "The diagnostics timeline data", auth: "Gate" },
  { name: "/api/dicom/*, /api/pathology/*", kind: "API", does: "Imaging catalogs, bytes, annotations, and slide tiles", auth: "Gate" },
  { name: "GET /api/education/*", kind: "API", does: "The public guides: manifest, pages, search, files", auth: "Public" },
  { name: "POST /api/publish/*", kind: "API", does: "The publish protocol the CLI speaks", auth: "Publish token" },
  { name: "oncobase init | sync | check | publish", kind: "CLI", does: "Set up a vault and run the publish loop", auth: "Publish token" },
  { name: "oncobase skills", kind: "CLI", does: "Copy the bundled agent skills into your vault", auth: "None" },
  { name: "oncobase elicit | transcription", kind: "CLI", does: "Literature, trials, and audio-to-note helpers", auth: "Service keys" },
  { name: "bun run local:stack", kind: "Script", does: "A complete local backend with seeded data", auth: "Local" },
];

export const detailItems: { title: string; text: string; proof?: string }[] = [
  { title: "No flash of the wrong theme", text: "Your theme is applied before the first paint, so dark mode never starts light.", proof: "index.html" },
  { title: "Links land where you meant", text: "Heading links and outline taps scroll clear of the fixed header, even after a reload, on phones and tablets.", proof: "Tested at 393px and 767px" },
  { title: "Background refreshes don't move you", text: "New content replaces old without resetting your scroll or your place in the navigation.", proof: "Tested" },
  { title: "Pages paint before the database opens", text: "A compressed snapshot paints the page and tree first, and is discarded if the account or access changed.", proof: "Tested" },
  { title: "Honest about slow and offline", text: "You see “Saved page · offline”, “N KB received” while bytes arrive, and a Retry that cancels the stalled request.", proof: "Tested" },
  { title: "Quiet loading", text: "Launch and “still loading” cues wait before appearing, and reduced-motion turns the pulse off.", proof: "Tested" },
  { title: "Layout that holds still", text: "A paint observer checks that content doesn’t jump while it loads, in CI, and images reserve their frame.", proof: "Dedicated CI workflow" },
  { title: "Shortcuts work before the app loads", text: "⌘K pressed during startup is queued and handed to the palette once it’s ready.", proof: "Tested across refresh" },
  { title: "Your layout is remembered", text: "Sidebar and rail widths, open folders, and recent files persist, and table column widths last for the session.", proof: "Automatic" },
  { title: "One-tap markdown handoff", text: "Copy a page as markdown with a single click and a check-mark to confirm. What you copy is already redacted.", proof: "Tested" },
  { title: "Real focus management", text: "Sheets trap Tab and restore focus, the lightbox is a native dialog, and the palette announces its result count.", proof: "Tested" },
  { title: "Accessibility checked by machine", text: "axe-core runs over the shell, search, comments, and viewers in light and dark; serious violations fail the build.", proof: "Tested" },
  { title: "Long pages stay fast", text: "Everything below the first screen is skipped until needed, while find-in-page, selection, anchors, and print still work.", proof: "Tested" },
  { title: "Search can’t go stale", text: "A late answer for an old query never replaces the current one, and interim results stay visible while the full scan finishes.", proof: "Tested" },
  { title: "Careful with files", text: "Only allowed file types are served, path tricks are rejected, large PDFs support range requests, and HTML is sandboxed.", proof: "Tested" },
  { title: "Private by default", text: "Gated and signed-in responses are never cached, sensitive pages are never indexed, and crawlers are told to stay out.", proof: "Tested" },
  { title: "Publishing you can trust", text: "Dry runs first, explicit flags for deletions, and success reported only after the reader confirms the pages.", proof: "CLI README" },
  { title: "Size budgets in CI", text: "The build fails if the entry or vendor bundles grow past their gzip limits.", proof: "check:bundle" },
];

const groupTitle = (id: GroupId) => groups.find((group) => group.id === id)!.title;

/** The text of `public/llms.txt`: a short index for agents. */
export function renderLlmsTxt(): string {
  return `# Oncobase

> Oncobase is an open-source (MIT) knowledge base for taking control of your care. Publish a vault of markdown notes, papers, and results to a searchable reader with AI search and chat, role-based privacy, inline redaction, and clinical viewers.

It was inspired by Sid Sijbrandij's osteosarc.com (https://osteosarc.com/).

## Start here

- [Everything Oncobase can do](${SITE_URL}/features): the public features page.
- [Full feature and interface list for agents](${SITE_URL}/llms-full.txt): every feature, where it lives, and how to call it.
- [Source code and README](${REPO_URL}): MIT licensed.
- [Diana's knowledge base](${SITE_URL}/): the first site built on Oncobase.

## What it does

${groups.map((group) => `- ${group.title}: ${group.tagline}`).join("\n")}

## Notes for agents

- The reader is a client-rendered web app; most content needs a signed-in session or the site password.
- The public guides at ${SITE_URL}/education and the features page need no password.
- To publish, use the \`oncobase\` CLI (\`oncobase check\`, then \`oncobase publish\`) and the bundled skills (\`oncobase skills\`).
`;
}

/** The text of `public/llms-full.txt`: everything, grouped, plus the interfaces. */
export function renderLlmsFullTxt(): string {
  const sections = groups
    .map((group) => {
      const items = groupFeatures(group.id)
        .map((feature) => `- **${feature.name}** — ${feature.summary} Where: ${feature.where}.${feature.surface ? ` Interface: \`${feature.surface}\`.` : ""}`)
        .join("\n");
      return `## ${group.title}\n\n${group.tagline}\n\n${items}`;
    })
    .join("\n\n");
  const table = [
    "| Name | Kind | What it does | Auth |",
    "| --- | --- | --- | --- |",
    ...interfaces.map((item) => `| \`${item.name}\` | ${item.kind} | ${item.does} | ${item.auth} |`),
  ].join("\n");
  const details = detailItems.map((item) => `- **${item.title}.** ${item.text}`).join("\n");
  return `# Oncobase: every feature

Oncobase is an open-source (MIT) knowledge base for taking control of your care. Source: ${REPO_URL}. Live example: ${SITE_URL}/. Inspired by Sid Sijbrandij's osteosarc.com (https://osteosarc.com/).

Auth key: Gate = the site's shared-password cookie; Session = an account cookie; Publish token = \`Authorization: Bearer wpt_…\`; Public = none.

${sections}

## Interfaces

${table}

## Details

${details}

Not available today: sorting or filtering inside tables, an MCP server, and automatic dark-theme swapping of illustration pairs inside the reader (illustrations are authored as light and dark pairs; pages like the landing and features pages pick the matching one).
`;
}

export { groupTitle };
