/**
 * The single source for the public features page and the agent-readable files
 * (`public/llms.txt` and `public/features.md`, generated by
 * `scripts/build-llms-txt.ts`). Only list what the code really does.
 */

import { DIANA_URL, REPO_URL, SITE_URL } from "./site";

export { REPO_URL, SITE_URL };

export type GroupId = "read" | "ask" | "protect" | "data" | "share" | "speed" | "build";

export type Feature = {
  group: GroupId;
  name: string;
  /** One plain sentence about what it does for the person using it. */
  summary: string;
  /** Where you find it. */
  where: string;
  /** How an agent or script reaches it, when it can. */
  surface?: string;
};

export const groups: { id: GroupId; title: string; tagline: string }[] = [
  { id: "read", title: "Read", tagline: "Find your way around and read comfortably, on any screen." },
  { id: "ask", title: "Ask", tagline: "Search by meaning, or talk to the knowledge base." },
  { id: "protect", title: "Protect", tagline: "Share the science without sharing the patient." },
  { id: "data", title: "See the data", tagline: "Timelines, scans, and slides next to the notes." },
  { id: "share", title: "Collaborate", tagline: "Bring family, doctors, and researchers in." },
  { id: "speed", title: "Speed", tagline: "Fast on the first visit, faster every visit after." },
  { id: "build", title: "Build", tagline: "Publish from plain files. Let your agent build with it." },
];

export const features: Feature[] = [
  // Read
  { group: "read", name: "Page tree", summary: "Every page in a folders-first tree that remembers what you opened, resizes, collapses to a rail, and stays fast on large vaults.", where: "Sidebar", surface: "GET /api/wiki/manifest" },
  { group: "read", name: "Outline", summary: "A page's headings with the current section highlighted as you scroll; a tab in the phone sheet and a mode in the palette.", where: "Right rail, phone sheet, palette (⌘⇧O)" },
  { group: "read", name: "Heading links", summary: "Every heading is linkable. Hover for a # that copies the URL, and deep links land clear of the fixed header.", where: "Every page" },
  { group: "read", name: "Smart tables", summary: "Column widths come from measured text, drag to resize, expand to the full workspace on desktop, with a phone layout and a sticky first column.", where: "Any markdown table" },
  { group: "read", name: "File palette", summary: "⌘K jumps to any page with fuzzy matching and recents, works offline, and also finds headings, source PDFs, tags, and actions.", where: "⌘K / Ctrl+K" },
  { group: "read", name: "Mobile reader", summary: "A phone header, a bottom sheet with Page nav and Outline tabs, focus trapping, and a floating Ask wiki button.", where: "Below 768px" },
  { group: "read", name: "Light, dark, or system", summary: "Three theme modes applied before first paint, so there is no flash. Diagrams follow the theme.", where: "Actions menu, palette, theme button" },
  { group: "read", name: "Image lightbox and slides", summary: "Open any image full screen with download, and step through a slide set with the arrow keys.", where: "Every page with images" },
  { group: "read", name: "Mermaid diagrams", summary: "Write a flowchart, timeline, or Gantt chart as text and it draws itself, follows your light or dark theme, and loads only on pages that use one.", where: "Any markdown page" },
  { group: "read", name: "Rich markdown", summary: "Wikilinks, GFM tables, task lists and footnotes, KaTeX math, citation links, and PDF chips.", where: "Every page" },
  { group: "read", name: "Tags and note bundles", summary: "Tag pages list their pages as a tree; Overview, Formatted, and Raw versions of one note share a switcher.", where: "/tags/:tag, page header" },
  { group: "read", name: "Saved pages and offline", summary: "Pages are stored on your device, paint before the database opens, and say plainly when you are offline or retrying.", where: "Automatic" },
  { group: "read", name: "Copy and download", summary: "Copy a page as markdown in one click, or download the whole wiki as a zip.", where: "Page header, actions menu", surface: "GET /api/page-copy, GET /api/download" },
  // Ask
  { group: "ask", name: "Chat with the knowledge base", summary: "An agent searches, reads the best pages, follows links, and answers with inline citations. Conversations are saved, and you can stop, queue, and resume.", where: "Ask wiki, /chat", surface: "POST /api/chat" },
  { group: "ask", name: "AI search", summary: "Semantic search that returns the most relevant pages, each scored out of 10 with a one-line reason.", where: "/search (AI Mode)", surface: "POST /api/ai-search" },
  { group: "ask", name: "Text search", summary: "Exact matches with line numbers and highlighted snippets, grouped by page, with an interim answer while the full scan finishes.", where: "/search (Text Search)", surface: "GET /api/search" },
  { group: "ask", name: "Agent tools", summary: "The same search and read tools the chat agent uses, as a JSON endpoint: search_wiki, read_page, get_pages_by_tag, list_tags, list_pages.", where: "API only", surface: "POST /api/tools" },
  // Protect
  { group: "protect", name: "Password gate", summary: "A shared password in front of the whole site, with a signed cookie and no-store responses.", where: "Sign-in page", surface: "POST /api/login" },
  { group: "protect", name: "Accounts and roles", summary: "Give each person a role and choose which folders and tags they can open. A sensitive page that no role matches is visible to nobody.", where: "Admin, Roles", surface: "/api/admin/roles" },
  { group: "protect", name: "Sensitive pages", summary: "Mark a page sensitive in its frontmatter and it drops out of guest manifests, search, AI search, chat, tags, downloads, link previews, and comments.", where: "Frontmatter", surface: "oncobase check" },
  { group: "protect", name: "Inline redaction", summary: "Wrap a span in <redact> or a block in :::redact and readers without access see the label, not the text.", where: "Markdown" },
  { group: "protect", name: "Redaction patterns", summary: "Per-site patterns catch identifiers that slip through, applied on page reads, search, AI search, chat, copy, and downloads.", where: "Site config" },
  { group: "protect", name: "Admin screens", summary: "Filter pages by who can see them, assign roles in bulk, and preview what a role includes before saving.", where: "/admin/pages, /admin/users, /admin/roles" },
  { group: "protect", name: "Agent skills for redaction", summary: "Written rules teach agents what to redact, what to leave visible, and what to mark sensitive, with a linter that checks.", where: "Vault skills (Diana’s vault)" },
  // See the data
  { group: "data", name: "Diagnostics timeline", summary: "Swim-lanes for imaging, pathology, ctDNA, and blood counts, with a draggable overview, zoom, filter, and source links.", where: "/diagnostics", surface: "GET /api/timeline" },
  { group: "data", name: "Imaging list", summary: "Every study with its reports, images, comparisons, and download, as a table or a phone list.", where: "/diagnostics/imaging", surface: "GET /api/diagnostic-studies" },
  { group: "data", name: "DICOM viewer", summary: "Stack and series browsing, window/level, pan, zoom, cine, touch gestures, deep links, and saved annotations with a calibrated ruler.", where: "/tools/dicom-viewer", surface: "/api/dicom/*" },
  { group: "data", name: "DICOM compare", summary: "Two synced viewports with presets such as subtraction, z-matched, and projection, and a clear match state.", where: "/tools/dicom-compare" },
  { group: "data", name: "Pathology slides", summary: "Whole-slide viewing with a navigator, magnification, scale bar, rulers, side-by-side compare, and saved region notes.", where: "/tools/pathology-viewer", surface: "/api/pathology/*" },
  { group: "data", name: "Lab ingestion", summary: "An hourly import of lab results from Epic MyChart over SMART on FHIR, with encrypted tokens.", where: "Admin", surface: "/api/integrations/epic/*" },
  // Share
  { group: "share", name: "Comments", summary: "Page-level and selection-anchored threads with replies, reactions, resolve, and shareable links; guests get a stable name.", where: "Right rail, /comments", surface: "/api/liveblocks-*" },
  { group: "share", name: "Link previews", summary: "Pages get their own preview card in chats and social apps. Sensitive pages fall back to a generic card.", where: "Automatic", surface: "GET /api/share-preview" },
  { group: "share", name: "Education hub", summary: "A public, password-free reader for the guides you choose to share, with its own search.", where: "/education", surface: "GET /api/education/*" },
  { group: "share", name: "Multi-site", summary: "One deployment can serve several sites, each with its own domain, password, roles, and data.", where: "Site config" },
  // Speed
  { group: "speed", name: "Local page store", summary: "Pages you have opened are kept in a local database in your browser, so reopening one or going back needs no network, and they still open offline.", where: "Automatic" },
  { group: "speed", name: "Whole index up front", summary: "The page tree, palette, and asset list come from one small manifest, so navigating and finding files never wait on the network.", where: "Automatic", surface: "GET /api/wiki/manifest" },
  { group: "speed", name: "Instant first paint", summary: "A compressed snapshot of the last page and tree paints before the database opens, and is dropped if your access changed.", where: "Automatic" },
  { group: "speed", name: "Destination first", summary: "Opening a page you haven’t visited shows its title and place in the tree right away, while the text arrives in one small request.", where: "Automatic" },
  { group: "speed", name: "Background prefetch", summary: "The pages other readers open most are fetched quietly ahead of time, up to 150 pages and 8 MiB, and never on offline or data-saver connections.", where: "Automatic", surface: "GET /api/wiki/prefetch" },
  { group: "speed", name: "Quiet revalidation", summary: "Unchanged data costs a tiny “not modified” reply instead of a download, and the page list refreshes at most about once a minute.", where: "Automatic" },
  { group: "speed", name: "Fast search", summary: "Search answers from an index within about a second and a half while the exhaustive scan finishes in the background.", where: "/search", surface: "GET /api/search" },
  { group: "speed", name: "Light code", summary: "Math, diagrams, chat, and the palette load only when a page needs them, and size budgets in the build keep the first download small.", where: "Automatic" },
  { group: "speed", name: "Long pages stay fast", summary: "Long articles skip drawing what is off screen, while find-in-page, selection, anchors, and print still work.", where: "Automatic" },
  // Build
  { group: "build", name: "Publish from a vault", summary: "Write in an Obsidian-style folder of markdown and publish with one command. Only changed files upload.", where: "Terminal", surface: "oncobase publish" },
  { group: "build", name: "Dry runs and safety rails", summary: "check shows what would change, tombstones need an explicit flag, dirty trees are refused, and uploads are verified by reading them back.", where: "Terminal", surface: "oncobase check" },
  { group: "build", name: "Sync", summary: "Pull remote content into the vault without overwriting your edits; differences are set aside for review.", where: "Terminal", surface: "oncobase sync" },
  { group: "build", name: "Embeddings", summary: "Publishing computes search embeddings so semantic search works the moment a page goes live.", where: "Terminal", surface: "oncobase publish --embeddings" },
  { group: "build", name: "Research helpers", summary: "Literature and clinical-trial search with provenance, and audio-to-note transcription.", where: "Terminal", surface: "oncobase elicit, oncobase transcription" },
  { group: "build", name: "Agent skills", summary: "Skills for first-time setup and safe pre-publish checks ship with the CLI and copy into your vault.", where: "Terminal", surface: "oncobase skills" },
  { group: "build", name: "Local stack", summary: "A self-hosted backend, seeded site, and smoke test on your machine, with no cloud account.", where: "Terminal", surface: "bun run local:stack" },
  { group: "build", name: "Open source", summary: "MIT licensed. Run it on Vercel and Convex or with the standalone Bun server.", where: "GitHub" },
];

export const heroLede =
  "A knowledge base for taking control of your care, built with attention to detail so it’s easy to read, easy to share, and safe.";

export type SectionId = "read" | "ask" | "protect" | "data" | "collaborate" | "speed" | "details" | "build";

/** The heading and introduction of each page section, shared by the page and features.md. */
export const sectionCopy: Record<SectionId, { kicker: string; heading: string; intro: string }> = {
  read: { kicker: "Read", heading: "Find your way, then read in peace.", intro: "Hundreds of pages should feel as easy as one. Everything below works on a laptop, a tablet, and a phone." },
  ask: { kicker: "Ask", heading: "Talk to the knowledge base.", intro: "Three ways to find things: exact words, meaning, and a conversation. Each one only ever sees what you’re allowed to see." },
  protect: { kicker: "Protect", heading: "Share the science without sharing the patient.", intro: "Privacy is built in layers, so a mistake in one doesn’t expose everything." },
  data: { kicker: "See the data", heading: "Results and scans, right beside the notes.", intro: "Clinical data is easier to understand next to the conversation about it. These viewers run in the browser, with nothing to install." },
  collaborate: { kicker: "Collaborate", heading: "Work through it together.", intro: "Family, doctors, and researchers read the same page, so the questions and answers live next to the thing they are about." },
  speed: { kicker: "Speed", heading: "Fast on the first visit, faster every visit after.", intro: "Reading shouldn’t wait on a spinner. Oncobase keeps what you have read on your device, loads the rest in the background, and downloads only the code a page needs." },
  details: { kicker: "The details", heading: "Built with attention to detail.", intro: "Caring for someone is full of small moments where software either helps or gets in the way. These are some of the small things we got right." },
  build: { kicker: "Build", heading: "Have your agent build your own knowledge base.", intro: "Use Oncobase as it is, or let your agent borrow from it while it builds yours. It’s MIT licensed, so use any part of the code any way you like." },
};

export const groupFeatures = (id: GroupId) => features.filter((feature) => feature.group === id);

/** Interfaces an agent or script can use. Auth: Gate = shared password cookie. */
export type InterfaceCategory = "content" | "ask" | "clinical" | "build";

export const interfaceCategories: { id: InterfaceCategory; title: string; summary: string }[] = [
  { id: "content", title: "Pages, files, and downloads", summary: "Read the wiki, its files, and the public guides." },
  { id: "ask", title: "Search, chat, and agent tools", summary: "Exact and semantic search, the chat agent, and its tools." },
  { id: "clinical", title: "Clinical data", summary: "The timeline, scans, and pathology slides." },
  { id: "build", title: "Publish and build", summary: "The CLI, the publish protocol, and local development." },
];

export const interfaces: { name: string; category: InterfaceCategory; kind: "API" | "CLI" | "Script"; does: string; auth: string }[] = [
  { name: "GET /api/wiki/manifest", category: "content", kind: "API", does: "File tree, page index, and asset index with ETag", auth: "Gate" },
  { name: "GET /api/wiki/pages?slugs=", category: "content", kind: "API", does: "Page bodies, redacted for the viewer", auth: "Gate" },
  { name: "GET /api/search?q=", category: "ask", kind: "API", does: "Exact-text search with line hits", auth: "Gate" },
  { name: "POST /api/ai-search", category: "ask", kind: "API", does: "Semantic search with relevance scores and summaries", auth: "Gate" },
  { name: "POST /api/chat", category: "ask", kind: "API", does: "Streaming agent chat with citations", auth: "Gate" },
  { name: "POST /api/tools", category: "ask", kind: "API", does: "Run search_wiki, read_page, get_pages_by_tag, list_tags, list_pages", auth: "Gate" },
  { name: "GET /api/page-copy?slug=", category: "content", kind: "API", does: "A page as a markdown download", auth: "Gate" },
  { name: "GET /api/download?type=", category: "content", kind: "API", does: "The whole wiki as a zip", auth: "Gate" },
  { name: "GET /api/file?path=", category: "content", kind: "API", does: "A PDF, image, or data file, with range requests", auth: "Gate" },
  { name: "GET /api/timeline", category: "clinical", kind: "API", does: "The diagnostics timeline data", auth: "Gate" },
  { name: "/api/dicom/*, /api/pathology/*", category: "clinical", kind: "API", does: "Imaging catalogs, bytes, annotations, and slide tiles", auth: "Gate" },
  { name: "GET /api/education/*", category: "content", kind: "API", does: "The public guides: manifest, pages, search, files", auth: "Public" },
  { name: "POST /api/publish/*", category: "build", kind: "API", does: "The publish protocol the CLI speaks", auth: "Publish token" },
  { name: "oncobase init | sync | check | publish", category: "build", kind: "CLI", does: "Set up a vault and run the publish loop", auth: "Publish token" },
  { name: "oncobase skills", category: "build", kind: "CLI", does: "Copy the bundled agent skills into your vault", auth: "None" },
  { name: "oncobase elicit | transcription", category: "build", kind: "CLI", does: "Literature, trials, and audio-to-note helpers", auth: "Service keys" },
  { name: "bun run local:stack", category: "build", kind: "Script", does: "A complete local backend with seeded data", auth: "Local" },
];

export type DetailGroup = "reading" | "speed" | "search" | "safe";

export const detailGroups: { id: DetailGroup; title: string; summary: string }[] = [
  { id: "reading", title: "Reading", summary: "Themes, links, refreshes, and layout behave." },
  { id: "speed", title: "Speed and connection", summary: "Loading that stays calm, on any network." },
  { id: "search", title: "Search, sharing, and publishing", summary: "Small guarantees around finding and sending things." },
  { id: "safe", title: "Safe and accessible", summary: "Private by default, and usable by everyone." },
];

export const detailItems: { group: DetailGroup; title: string; text: string }[] = [
  { group: "reading", title: "No flash of the wrong theme", text: "Your light or dark choice is applied before anything draws, so dark mode never starts out white." },
  { group: "reading", title: "Links land where you meant", text: "Heading links and outline taps scroll clear of the header, even after a reload, on a phone or a laptop." },
  { group: "reading", title: "Refreshes don’t move you", text: "New content slips in without losing your scroll position or your place in the navigation." },
  { group: "speed", title: "Honest about slow and offline", text: "You see “Saved page · offline” or how much has arrived, with a Retry if a page stalls." },
  { group: "speed", title: "Quiet loading", text: "Loading cues wait a beat before appearing, and turn their motion off if you prefer reduced motion." },
  { group: "reading", title: "Your layout is remembered", text: "Sidebar and panel widths, open folders, and recent files are right where you left them." },
  { group: "speed", title: "Shortcuts work right away", text: "Press ⌘K while the page is still starting up and the palette opens as soon as it’s ready." },
  { group: "safe", title: "Checked for accessibility", text: "Automated checks run over the reader, search, comments, and viewers in light and dark." },
  { group: "search", title: "Search stays in step", text: "A slow answer for an old search never replaces the one you just ran." },
  { group: "safe", title: "Private by default", text: "Signed-in pages are never cached, sensitive pages are never indexed, and crawlers are told to stay out." },
  { group: "search", title: "One-tap markdown handoff", text: "Copy a page as markdown with a single click and a check-mark. What you copy is already redacted." },
  { group: "search", title: "Publishing you can trust", text: "A dry run first, an explicit flag for deletions, and success reported only after the pages are live." },
];

/** The text of `public/llms.txt`: a short index for agents. */
export function renderLlmsTxt(): string {
  return `# Oncobase

> Oncobase is an open-source (MIT) knowledge base for taking control of your care. Publish a vault of markdown notes, papers, and results to a searchable reader with AI search and chat, role-based privacy, inline redaction, and clinical viewers.

It was inspired by Sid Sijbrandij's osteosarc.com (https://osteosarc.com/).

## Start here

- [Oncobase](${SITE_URL}/): what it is and who it is for.
- [Everything Oncobase can do](${SITE_URL}/features.md): every feature, where it lives, and how to call it, in markdown. The same content as the [features page](${SITE_URL}/features).
- [How Oncobase compares](${SITE_URL}/compare.md): when to use Notion, Obsidian, Yuga Bio, and others instead, and what to reuse if you are building your own. The same content as the [comparison page](${SITE_URL}/compare).
- [Source code and README](${REPO_URL}): MIT licensed.
- [Diana's knowledge base](${DIANA_URL}/): the first site built on Oncobase.

## Two ways to use it with an agent

- Have your agent build your own knowledge base with the \`oncobase\` CLI (\`oncobase check\`, then \`oncobase publish\`) and the bundled skills (\`oncobase skills\`).
- Or have your agent reference Oncobase while it builds yours: the code is MIT licensed, so any part can be read, copied, and adapted.

## Notes for agents

- The reader is a client-rendered web app; most content needs a signed-in session or the site password.
- The public guides at ${DIANA_URL}/education need no password, and neither do this site's pages (the home page, features, and compare).
`;
}

const bullet = (feature: Feature) =>
  `- **${feature.name}.** ${feature.summary} Where: ${feature.where}.${feature.surface ? ` Interface: \`${feature.surface}\`.` : ""}`;

/** The text of `public/features.md`: the features page as markdown, for people and agents. */
export function renderFeaturesMd(): string {
  const sectionGroup: Partial<Record<SectionId, GroupId>> = {
    read: "read", ask: "ask", protect: "protect", data: "data", collaborate: "share", speed: "speed", build: "build",
  };
  const order: SectionId[] = ["read", "ask", "protect", "data", "collaborate", "speed", "details", "build"];
  const sections = order
    .map((id) => {
      const copy = sectionCopy[id];
      const head = `## ${copy.heading}\n\n${copy.intro}`;
      if (id === "details") {
        const body = detailGroups
          .map((group) =>
            [`### ${group.title}`, "", ...detailItems.filter((item) => item.group === group.id).map((item) => `- **${item.title}.** ${item.text}`)].join("\n"),
          )
          .join("\n\n");
        return `${head}\n\n${body}`;
      }
      const group = sectionGroup[id]!;
      const list = groupFeatures(group).map(bullet).join("\n");
      if (id !== "build") return `${head}\n\n${list}`;
      const tables = interfaceCategories
        .map((category) =>
          [
            `### ${category.title}`,
            "",
            "| Name | Kind | What it does | Auth |",
            "| --- | --- | --- | --- |",
            ...interfaces
              .filter((item) => item.category === category.id)
              .map((item) => `| \`${item.name}\` | ${item.kind} | ${item.does} | ${item.auth} |`),
          ].join("\n"),
        )
        .join("\n\n");
      return `${head}\n\n${list}\n\n### Start\n\n\`\`\`\noncobase init --site my-site --vault ./vault --publish-url https://my-site.example\noncobase skills\noncobase check\noncobase publish --embeddings auto\n\`\`\`\n\n### Interfaces\n\nAuth: Gate = the site's shared-password cookie; Session = an account cookie; Publish token = \`Authorization: Bearer wpt_…\`; Public = none.\n\n${tables}`;
    })
    .join("\n\n");
  return `# Everything Oncobase can do

> ${heroLede}

Source: ${REPO_URL} (MIT). Live example: ${DIANA_URL}/. This page: ${SITE_URL}/features. How it compares with Notion, Obsidian, and others: ${SITE_URL}/compare.md. Inspired by Sid Sijbrandij's osteosarc.com (https://osteosarc.com/).

${sections}

## Not available today

Sorting or filtering inside tables, and an MCP server.
`;
}
